### ISSUE TITLE
System.Management.ManagementException: Not found

### ISSUE THREAD

**Issue by aadi1295** [MatthewKing/DeviceId#17]
Hey MatthewKing,
Congrats for this amazing work.
I am getting the following error on Windows 8.1 64bit (Not virtual OS) and I am using DeviceId 4.5.0. Will upgrading to 5.1.1 change the DeviceId output? and is there a way to check for each user if all the required IDs are available or not before generating the final client device ID in  DeviceIdBuilder()?

I am using 
```
                string deviceId = new DeviceIdBuilder()
                .AddMachineName()
                .AddProcessorId()
                .AddMotherboardSerialNumber()
                .AddSystemDriveSerialNumber()
                .ToString();
```

The client is saying that WMI is running, so I am not sure what is missing from the above 4 required IDs. 
Please see the error detail below

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.Management.ManagementException: Not found
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementClass.GetInstances(EnumerationOptions options)
   at System.Management.ManagementClass.GetInstances()
   at DeviceId.Components.WmiDeviceIdComponent.GetValue()
   at DeviceId.Formatters.HashDeviceIdFormatter.<>c.<GetDeviceId>b__3_1(IDeviceIdComponent x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DeviceId.Formatters.HashDeviceIdFormatter.GetDeviceId(IEnumerable`1 components)
   at DeviceId.DeviceIdBuilder.ToString()
   at DatalayerClass.<>c__DisplayClass18_0.<Get_Unique_Device_Id>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by MatthewKing** [comment]
I'm no WMI expert, but I think that the error message you're seeing indicates that something has gone wrong with WMI on your machine. I've done a quick search for that particular error message and it seems to be quite common (and unrelated to DeviceId in particular). There seems to be a lot of different suggested fixes. As I've never encountered this issue myself, I can't recommend which fix you try.

Upgrading from v4 to v5 will _probably_ keep your device IDs the same, but I think there was a potential for them to change in some edge cases (hence the major version increment). Having said that, I don't think upgrading from v4 to v5 will help in this case. I'm going to have to reconsider how DeviceId should act in the case of exceptions like this. I'm not sure whether throwing the exception is good behavior or not.

But to fix your actual issue, I think you're going to have to resolve the issue with WMI on your system.

**Comment by aadi1295** [comment]
Thanks for your reply, I think user's WMI is corrupt. 
Can you please check the email on your email mking@mking.net regarding this Github issue. 
I really appreciate your help. Thanks again
